#!/usr/bin/env bash

if [ -z "${PORT}" ]; then
  uvicorn --port 8080 --host 0.0.0.0 fakeurldetector.API:FakeURLDetection
else
  uvicorn --port "${PORT}" --host 0.0.0.0 fakeurldetector.API:FakeURLDetection
fi
