name: SafeURL Detector Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  BuildWheel:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/URLRakshak
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.6
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Install deps for Pypi Release
        run: |
          pip -q install setuptools wheel
          pip -q install -r requirements.txt
      - name: Build Artifacts
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Sleep
        run: sleep 60
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Docker meta
        id: metaraw
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/viswanathbalusu/urlrakshak
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.build
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metaraw.outputs.tags }}
          labels: ${{ steps.metaraw.outputs.labels }}